# Generated by Django 4.2.25 on 2025-10-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile_bags_picked_profile_display_name_pickup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="listing_pics"),
        ),
    ]
