# Generated by Django 4.2.25 on 2025-11-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='sustainability_interests',
            field=models.TextField(blank=True, help_text='Your sustainability interests', max_length=500),
        ),
    ]
