# Generated by Django 4.2.24 on 2025-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_profile_bio_profile_sustainability_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_notifications",
            field=models.BooleanField(
                default=False, help_text="Receive email notifications for new messages"
            ),
        ),
    ]
