# Generated by Django 4.2.24 on 2025-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_profile_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="school_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "First Year"),
                    ("second", "Second Year"),
                    ("third", "Third Year"),
                    ("fourth", "Fourth Year"),
                    ("grad", "Graduate Student"),
                    ("other", "Other"),
                ],
                help_text="Your current year at UVA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="setup_complete",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed first-time setup",
            ),
        ),
    ]
