# Generated by Django 4.2.25 on 2025-12-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_listing_options_listing_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
    ]
