# Generated by Django 4.2.25 on 2025-12-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated topic tags for discoverability'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='inapp_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable in-app notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_group_added',
            field=models.BooleanField(default=True, help_text='Notify when added to a group chat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_message_request',
            field=models.BooleanField(default=True, help_text='Notify when someone wants to message you'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_message',
            field=models.BooleanField(default=True, help_text='Notify when you receive a new message'),
        ),
        migrations.CreateModel(
            name='BanAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='appeal_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
