# Generated by Django 4.2.24 on 2025-12-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("message_request", "Message Request"),
                    ("group_added", "Added to Group Chat"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
